### ISSUE TITLE
Empty title tags

### ISSUE THREAD

**Issue by killercup** [yoshuawuyts/blog#9]
Hey, just saw you link https://blog.yoshuawuyts.com/rust-2019/ on Twitter and spent half a minute figuring out why Firefox wasn't showing the tab's title. Turns out your HTML contains an empty title tag!

Now, onto reading the post!

**Comment by yoshuawuyts** [comment]
@killercup haha, excellent catch. I'll make sure to fix this soonish!

**Comment by yoshuawuyts** [comment]
Fixed! :D
